apiVersion: v1
kind: Secret
metadata:
  name: gitops-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
data:
  passwordSecret: "Z2hwX045ZU1YT0ZyZ0pYVnhzNXE0N3RXS29hb0h0WlZ4bTJmMVZmZw=="
  usernameSecret: "TW9oemVlbGE="
  gitops_project_base64: "bW9o"
  gitops_type_base64: "Z2l0"
  url: "aHR0cHM6Ly9naXRodWIuY29tL3dhbGVtby9Bei1naXRvcHMuZ2l0"
type: Opaque

